version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: sendspark_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    image: mongo
